<?php

// Environment-specific URLs
if ($_SERVER["SERVER_NAME"] == "localhost") {
    define("ROOT_IMAGE", "http://localhost/framework/public/assets/images/");
    define("ROOT_CSS", "http://localhost/framework/public/assets/css/");
    define("ROOT_JS", "http://localhost/framework/public/assets/js/");
} else {
    define("ROOT", "http://www.mywob/framework/public");
}

// Debug mode
define("DEBUG", true);

// === Add your DB and site config below ===
// These will be overwritten/generated by your CLI setup script

define('DB_HOST', 'localhost');     // default host
define('DB_NAME', 'your_db_name');  // placeholder
define('DB_USER', 'root');  
define('DB_PASS', '');  // 

define('SITE_NAME', 'My Website');  
